/**
 * Build-time pack bundler.
 *
 * Emits `src/packs.generated.ts`: a static, filesystem-free module carrying
 * every discovered pack's data and a static import of its generators. The
 * Cloudflare Worker entry imports it and calls `assembleLoaded` — the exact
 * assembly the fs loader (`loadAllPacks`) uses — so the Worker serves the same
 * graph without the `node:fs` scan and dynamic `import()` that don't exist on
 * Workers (see docs/deploy/hitl-checklist.md §4).
 *
 * Run: `pnpm bundle-packs` (also runs before tests and before deploy).
 * The output is committed and MUST be regenerated when packs change; the
 * equivalence test (`packs-bundle.test.ts`) fails if it drifts.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { discoverPacks, loadPack } from "../src/pack-loader.js";

const OUT = new URL("../src/packs.generated.ts", import.meta.url);

/** A pack dir name to a valid JS identifier for its generator import. */
function ident(dirName: string): string {
  return `g_${dirName.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

async function renderBundle(): Promise<string> {
  const packs = await Promise.all(discoverPacks().map(loadPack));

  const imports: string[] = [];
  const rows: string[] = [];
  for (const p of packs) {
    // A pack owns generators iff it ships an index.ts. Import them statically —
    // that is the whole trick: the specific packs are known at build time, so
    // there is nothing to import dynamically. `dir` is a placeholder here: the
    // assembly path never dereferences it (only the fs loader does).
    const hasGenerators = existsSync(new URL("index.ts", p.dir));
    if (hasGenerators) {
      imports.push(`import { generators as ${ident(p.dirName)} } from "../../../packs/${p.dirName}/index.js";`);
    }
    rows.push(
      [
        "  {",
        `    id: ${JSON.stringify(p.id)},`,
        `    dirName: ${JSON.stringify(p.dirName)},`,
        `    dir: new URL(${JSON.stringify(`pack:///${p.dirName}/`)}),`,
        `    manifest: ${JSON.stringify(p.manifest)},`,
        `    entities: new Map(${JSON.stringify([...p.entities.entries()])}),`,
        `    statements: ${JSON.stringify(p.statements)},`,
        `    generators: ${hasGenerators ? ident(p.dirName) : "{}"},`,
        "  }",
      ].join("\n"),
    );
  }

  return `${[
    "// AUTO-GENERATED by scripts/bundle-packs.ts — do not edit.",
    "// Regenerate with `pnpm bundle-packs` whenever packs change.",
    "// The equivalence test (packs-bundle.test.ts) fails if this drifts from disk.",
    'import type { LoadedPack } from "./pack-loader.js";',
    imports.join("\n"),
    "",
    "export const loadedPacks: LoadedPack[] = [",
    rows.join(",\n"),
    "] as LoadedPack[];",
    "",
  ].join("\n")}`;
}

const source = await renderBundle();
// Skip the write when nothing changed: this file lives under src/, which the
// `wrangler dev` watcher observes, so rewriting it byte-identical on every build
// would trigger an endless rebuild loop (the deploy [build] step reruns us).
const unchanged = existsSync(OUT) && readFileSync(OUT, "utf8") === source;
if (unchanged) {
  console.log(`unchanged ${fileURLToPath(OUT)} (${source.length} bytes)`);
} else {
  writeFileSync(OUT, source);
  console.log(`wrote ${fileURLToPath(OUT)} (${source.length} bytes)`);
}
