/**
 * `pnpm --filter @geo/web generate-world-map` — bakes the world land silhouette
 * into `src/world-map.generated.ts` as one SVG path string *per offered
 * projection* (`WORLD_LAND_PATHS`, keyed by projection id).
 *
 * MapAid draws no map library at runtime; it just renders the baked path for the
 * active projection. The generation is author-time only (mirrors
 * `packages/server`'s `packs.generated` pattern): Natural Earth land (public
 * domain, via `world-atlas`) projected through each registry entry's own d3
 * `GeoProjection` — the same one MapAid plots points in — so every layer shares
 * one coordinate space (#217). Add a projection to `PROJECTIONS` and its land
 * path is baked here automatically.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { geoPath } from "d3-geo";
import { feature } from "topojson-client";
import { PROJECTIONS, type ProjectionId } from "../src/projection.js";

const require = createRequire(import.meta.url);
// 110m resolution: coarse, but tiny and legible on a small card. Public domain.
const land = require("world-atlas/land-110m.json");

const landGeo = feature(land, land.objects.land) as unknown as Parameters<
  ReturnType<typeof geoPath>
>[0];

// One baked path per projection: same registry entry, same d3 `GeoProjection`
// MapAid uses at runtime, so the path and the plotted points align (#217).
const paths: (readonly [ProjectionId, string])[] = PROJECTIONS.map((p) => {
  const d = geoPath(p.factory())(landGeo);
  if (!d) throw new Error(`failed to generate world land path for ${p.id}`);
  return [p.id, d] as const;
});
const body = paths
  .map(([id, d]) => `  ${JSON.stringify(id)}: ${JSON.stringify(d)},`)
  .join("\n");

const out = fileURLToPath(new URL("../src/world-map.generated.ts", import.meta.url));
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/generate-world-map.ts — do not edit.
// Regenerate with \`pnpm --filter @geo/web generate-world-map\`.
// Natural Earth 110m land (public domain), one path per projection over a 0 0 360 180 box.
import type { ProjectionId } from "./projection.js";

export const WORLD_LAND_PATHS: Record<ProjectionId, string> = {\n${body}\n};\n`,
);

console.log(
  `✓ wrote world-map.generated.ts (${paths.length} projections: ${paths
    .map(([id, d]) => `${id} ${d.length}ch`)
    .join(", ")})`,
);
