/**
 * `pnpm --filter @geo/web generate-world-map` — bakes the world land silhouette
 * into `src/world-map.generated.ts` as a single SVG path string.
 *
 * MapAid draws no map library at runtime; it just renders this baked path. The
 * generation is author-time only (mirrors `packages/server`'s `packs.generated`
 * pattern): Natural Earth land (public domain, via `world-atlas`) projected onto
 * the same equirectangular `0 0 360 180` viewBox MapAid plots points in, so the
 * path and the point share one coordinate system.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { geoEquirectangular, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
// 110m resolution: coarse, but tiny and legible on a small card. Public domain.
const land = require("world-atlas/land-110m.json");

// Match MapAid's projection exactly: lon [-180,180] → x [0,360], lat [90,-90] →
// y [0,180]. geoEquirectangular is plate carrée; scale 180/π + translate makes
// one radian of longitude one degree of x.
const projection = geoEquirectangular()
  .scale(180 / Math.PI)
  .translate([180, 90]);

const landGeo = feature(land, land.objects.land) as unknown as Parameters<
  ReturnType<typeof geoPath>
>[0];
const d = geoPath(projection)(landGeo);
if (!d) throw new Error("failed to generate world land path");

const out = fileURLToPath(new URL("../src/world-map.generated.ts", import.meta.url));
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/generate-world-map.ts — do not edit.
// Regenerate with \`pnpm --filter @geo/web generate-world-map\`.
// Natural Earth 110m land (public domain), equirectangular over a 0 0 360 180 viewBox.
export const WORLD_LAND_PATH =\n  ${JSON.stringify(d)};\n`,
);

console.log(`✓ wrote world-map.generated.ts (${d.length} chars of path data)`);
